plugins {
    id 'com.android.application'
}

android {
    namespace 'com.juanito.tvcleaner'
    compileSdk 34

    defaultConfig {
        applicationId "com.juanito.tvcleaner"
        minSdk 22          // cubre Android 5.1 en adelante (Onn y Google TV)
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            // Sin ofuscacion para que compile facil en GitHub Actions / Android Studio
            minifyEnabled false
            // Firma con la clave de depuracion para que el APK sea instalable
            // directamente. Suficiente para uso personal (no para Play Store).
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.recyclerview:recyclerview:1.3.2'
    implementation 'androidx.leanback:leanback:1.0.0'
}
